### ISSUE TITLE
Open background info in new tab

### ISSUE THREAD

**Issue by astrosnat** [openpredictionmarkets/socialpredict#106]
Not urgent to implement.

Have been using the [Social Science Prediction Project](https://socialscienceprediction.org/). They have the option to open background info in a new tab, so that participants in a prediction market can easily access that information later. Could be useful if a prediction market is especially technical.

**Comment by pwdel** [comment]
So is this just analogous to comments? Or is this more, "background information added by an admin?"

One philosophy is, "comments" which is essentially, "anyone on the platform adding background information."

Another is, "only the admin can add relevant information."

Yet another could be, "issues," or, "threads," which...could be sort of analogous to comments, but rather than being a vector of comments ordered by time, they could be a sort of notion or idea that gets opened/closed with discussion comments attached over time on a given issue, more analogous to a discussion forum. Closed issues could still be viewed, but the discussion on that issue could at least be grouped.

An informal group trying to figure out an issue will just have people shouting whatever they think is relevant over time, as a sort of conversation, this would be more analogous to comments.

A committee or body abiding by Robert's Rules of Order might take up an issue, vote to discuss an issue, then either close or re-open an issue for vote...this is more analogous to, "issues."

**Comment by pwdel** [comment]
To a certain extent, this problem may have been arguably solved by adding links to Google Docs or online docs from a description.

It seems like explicitly adding verified background information as a new tab might be a, "nice to have," within the application itself, when any user of SocialPredict can hypothetically link elsewhere online.

We're not necessarily trying to hold people into a walled garden, e.g. hypothetically we're not running the site, and we're neutral as far as keeping people on whatever www.predictionsite.whatever because we don't know if the admin cares about keeping people solely on their site or is OK with linking them off to other sites. Seems like we should be non-opinionated here.

If you're amenable to it @astrosnat I would like to close this discussion and open up another discussion for a far-future feature, which is the concept of, "issue tracking," within the comments section of a given market, rather than just a pure string of comments.

The idea I have behind, "issue tracking," vs. "comments," is that ... often times on Manifold I have noticed that the same topic gets brought up again and again on comments on a long-ranging market. Sometimes the issue gets brought up repeatedly because you have new market participants who are just not familiar with the details of the market. Other times you have people attempting to, "get attention," and manipulate the market toward their price by just posting the same propaganda over and over again (whether that propaganda is useful or not).

Issue tracking would replace the comments with more of either a discussion-forum style listing with topic headers, or issues which could be pinned, and each issue could have its own discussion within it. So while people could of course gamify issues by myopically bringing up the same concepts across multiple issues, it would at least give the ability for users to sort for issues and information that they deem relevant from the start.

Issues that get more volume and comments might percolate up to the top whereas issues without as much volume might move downward. There might be a simple algorithm that simply ranks issues by sheer volume, or there might be an algorithm that ranks by recent volume.

**Comment by astrosnat** [comment]
@pwdel yes, totally happy to close, and then discuss issue tracking in another discussion
