### ISSUE TITLE
v0.0.3 tag after successful deployment and testing, documentation

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#171]
This branch will include documentation as well as fixes needed for a basic deployment on Digital Ocean.

https://github.com/openpredictionmarkets/socialpredict/pull/157

To get this done first we need to finish:

https://github.com/orgs/openpredictionmarkets/projects/1/views/1?pane=issue&itemId=70635318

AND 

https://github.com/orgs/openpredictionmarkets/projects/1/views/1?pane=issue&itemId=70635341

**Comment by pwdel** [comment]
Plan To Get This Done:

* Track all environmental variables which must be kept secret
* Set up firewall and document (done)
* Update CORS policies
*

**Comment by pwdel** [comment]
Different nginx direction:

https://blog.kronis.dev/tutorials/how-to-use-nginx-to-proxy-your-front-end-and-back-end

**Comment by pwdel** [comment]
Putting notes here after completion of recent v0.0.3-prod.

https://github.com/openpredictionmarkets/socialpredict/blob/deploy_prod/CHANGES.md

Reflecting on attempting to run the above per the instructions.

**Comment by pwdel** [comment]
Questions:

1. Why do we need to do `chmod +x SocialPredict` after cloning the repo? Can't we make this executable prior to committing to the repo so that it is executable to begin with to save a step?
2. For documentation purposes do we need to explicitly state how to use nslookup since it is aimed at less highly techincal users? E.g.:

```
root@breirfoxforecast-alpha:/home/testdeploy/socialpredict# nslookup -type=A brierfoxforecast.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	brierfoxforecast.com
Address: 143.198.177.112

root@breirfoxforecast-alpha:/home/testdeploy/socialpredict# nslookup -type=A www.brierfoxforecast.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	www.brierfoxforecast.com
Address: 143.198.177.112
```
3. Reflecting on the interface.

```
### Building and Deploying SocialPredict ...

### Checking that docker compose is installed ...
Found docker compose.

### First time running the script ...
### Let's initialize the appliction ...
What domain do you wish to use for the application?
```
* Should we give an example of how the domain should be formatted at this point?
* Should we run the nslookup for the user at this point?

4. Having done the following, do we need to create an example in the documentation and explicitly state this out that the email must be owned and valid?:

```
### First time running the script ...
### Let's initialize the appliction ...
What domain do you wish to use for the application? brierfoxforecast.com
Setting DOMAIN to: brierfoxforecast.com

What email address do you wish to use for the SSL Certificate? email@email.com
Setting EMAIL to: email@email.com
```

5. Should we recommend a random user and password? Should we ask the user to save this for future access..?

```
Specify username for the Database User. (default: user)
```

6. How important is it to obscure the password during setup? Should we not allow a default password that is, "password," since this is unsecure?

```
Specify username for the Database User. (default: user) whateveruser
Setting Database User to: whateeveruser

Specify password for the Database User. (default: password) ********
Setting Database Password to: ********
```
7. No notes here, seems fine. Is there any security risk in keeping the same name?

```
Specify the name for the Database. (default: socialpredict_db)
```
8. Should not have a default here. Risky an insecure if kept the same as hackers could see it in the code.

```
Specify the password for the Admin User. (default: adminpass)
```

9. Another thought, so basically it seems like this is a one time script, as we are completely restarting the database, there is no option to use a backup database.

We might consider creating an idempotent branch of this so it  could be a more universal tool, used as a hard reboot, which does not effect the database.

Yet another thought, I believe if you use a docker database, it saves the data in a hard location. A couple thoughts ... do we want to eventually build a way to mount a database from an external service? Or create a backup to S3 option? Do we want the ability to back up and re-load data at various states, prior to running the prod boot code?

```
Specify the password for the Admin User. (default: adminpass) mushyStubsIgniteDevotee
Setting Admin Password to: ********

### Searching for .env file ...
.env file found.
```

10. Are we going to want to create pre-built packages in the future rather than have individuals build it on their server? Seems like a want more than a need.

```
Searching for Backend Image ...
### Searching for Docker Images ...
Searching for Backend Image ...
Backend Image Found. Do you want to re-build it? (y/N)
```

11. Error at end.

```
Using Domain brierfoxforecast.com for the deployment.
### Downloading recommended TLS parameters ...

### Creating dummy certificate for brierfoxforecast.com ...
[+] Running 1/1
 ✔ Network scripts_default  Created                                                                                                   0.2s
....+...+..+....+..+...+................+........+...+.......+++++++++++++++++++++++++++++++++++++++++++++*.+...+.....+.+.....+......+++++++++++++++++++++++++++++++++++++++++++++*.+........+.+............+.....+.......+..+....+++++
....+++++++++++++++++++++++++++++++++++++++++++++*......+..+....+++++++++++++++++++++++++++++++++++++++++++++*.+......+........+.......+........+............+....+.........+++++
-----

### Starting Webserver ...
[+] Running 1/1
 ✔ Container socialpredict-nginx-container  Started                                                                                   0.7s

### Deleting dummy certificate for brierfoxforecast.com ...

### Requesting Let's Encrypt Certificate for brierfoxforecast.com ...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for brierfoxforecast.com

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/brierfoxforecast.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/brierfoxforecast.com/privkey.pem
This certificate expires on 2024-10-11.
These files will be updated when the certificate renews.

NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

### Shutting down Webserver ...
[+] Running 2/2
 ✔ Container socialpredict-nginx-container  Removed                                                                                   0.3s
 ✔ Network scripts_default                  Removed                                                                                   0.1s
[+] Running 5/5
 ✘ db Error                                                                                                                           0.2s
 ✘ backend Error                                                                                                                      0.2s
 ✘ frontend Error                                                                                                                     0.2s
 ✘ webserver Error                                                                                                                    0.2s
 ✘ certbot Error                                                                                                                      0.2s
Error response from daemon: pull access denied for socialpredict-backend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
root@breirfoxforecast-alpha:/home/testdeploy/socialpredict#
```

**Comment by ntoufoudis** [comment]
Replying to your questions:

1. The script is already set to be executable, but with so many different OS, versions, software, user modifications etc. we cannot be certain that it will remain executable after cloning the repository. That is why I put that there. 

2. No we don't. I added it as a "check mechanism" that can help verify that the domain is pointing to the server, but after further consideration I think we should remove it because it can provide false positives if someone is using a service like Cloudflare. With so many different registrars and different options out there, there isn't a 1-guide fits all for providing information on how to update DNS settings and how to verify them. There are some general guidelines but they can't fit 100% on each individual case.

3. Yes we can provide an example on how to input the domain. Also I should add an extra function here to determine if the user wants to use the www version or the non www version of the domain an update the files accordingly. We cannot use nslookup here for verification since as I mention on 2. it can provide false positives. We can come up with a different approach, like the one used by Certbot, to create a random file and check if it is accessible by the internet using the specified domain, but let's leave it for a next version since it is a kind of tricky approach to implement.

4. Yes we should. While it is not necessary to provide a valid email address or provide an email address at all, it is advised since it will be used by Let's Encrypt to communicate any security issues or when the certificate is about to expire.

5. We can either ask the user to input a user and password or we can generate random inputs. Either way the values will be stored in the .env file and used by the database and backend containers to communicate with each other. There is no need for the user to store them since they will already be stored in the .env file.

6. We can either obscure the password as "*" or leave the input empty as the user types the password. We can set some rules that will require the password to be a certain length or require capital letters or symbols etc.

7. No there is no issue in keeping the same name. I just added as an extra option for the user.

8. Here the ideal approach would be the backend to generate a random password for the admin user when seeding the database for the first time, then echo the password to the user, and finally force the user to change the admin password on first login.

10. Yes, for a production setup we should have a backend image hosted on docker hub where the user will just pull the image from there without needed to build anything on their machine and the static files should be built and downloaded as is on the user's server.

11. I will fix that.

12. Notes on 9. and some personal thoughts:
* This script should be a standalone script that the user can download and run.
* The script should ask the user input on application environment (development or production) and then proceed to download or clone all the required files and perform all the necessary actions to build the application and serve it for the user.
* We should add the option for the script to backup or restore the database.
* We should add the option for the script to ask if the user wants to import a database backup or use a clean one.
* Storing the database backup to an external service like S3 is something we can provide.
* Providing an option to use an external service is possible, but will require some technical knowledge of the user, because they will need to make sure their external database can be access by their server. That mean firewall adjustments, or creating new IAM roles if they are on AWS etc. It is possible to provide this option, but it cannot be offered in a way that the end user can just opt to do. They will need some technical background, and with so many different option we cannot provide documentation for each one of them.

**Comment by pwdel** [comment]
Thank you. Follow Up Ticket on this conversation:

https://github.com/openpredictionmarkets/socialpredict/issues/209

**Comment by pwdel** [comment]
Responding to 8. https://github.com/orgs/openpredictionmarkets/projects/4/views/1?pane=issue&itemId=71007259

**Comment by pwdel** [comment]
Responding to:

> Storing the database backup to an external service like S3 is something we can provide.
> Providing an option to use an external service is possible, but will require some technical knowledge of the user, because they will need to make sure their external database can be access by their server. That mean firewall adjustments, or creating new IAM roles if they are on AWS etc. It is possible to provide this option, but it cannot be offered in a way that the end user can just opt to do. They will need some technical background, and with so many different option we cannot provide documentation for each one of them.


https://github.com/orgs/openpredictionmarkets/projects/5/views/1?pane=issue&itemId=71007758

**Comment by pwdel** [comment]
Attempting to close out these security concerns:

![Image](https://github.com/user-attachments/assets/4780dc6a-35eb-4e87-9f11-8e446bc9fb63)

As well as add last minute load testing documentation and work out any final bugs before going to v0.0.4

**Comment by pwdel** [comment]
DONE! https://github.com/openpredictionmarkets/socialpredict/tree/v0.0.3
