### ISSUE TITLE
Towards Running SocialPredict on Windows

### ISSUE THREAD

**Issue by astrosnat** [openpredictionmarkets/socialpredict#195]
Osnat to test whether Docker can work with WSL2 and whether a SocialPredict instance can be built on a Windows machine.

**Comment by astrosnat** [comment]
Osnat tested with WSL2, Windows 11 and Docker for WSL2.

Result: SocialPredict instance can be built on Windows machine.

**Comment by pwdel** [comment]
That's awesome. 

If you wanted to close the loop and see more about how the git development process works (if you're not already familiar) you could..

1. Pull from main
2. Create a new branch off of main.
3. Make some modifications to https://github.com/openpredictionmarkets/socialpredict/blob/main/README/LOCAL_SETUP.md which currently says, "Windows Support Not Guaranteed." ... we should probably have a header, "Supported Systems" toward the top as a prerequisite rather than as a bullet point under another header.
4. Push this change to your branch and create a merge request (after you push, it will give you a link you can copy/paste from the terminal).
5. Add me as a reviewer and I can approve it, then you can merge to master.

Otherwise, we need a ticket so that this gets updated in at least the next cycle, v0.0.4 or something.
