### ISSUE TITLE
Towards local Windows installs with Docker and WSL2

### ISSUE THREAD

**Issue by astrosnat** [openpredictionmarkets/socialpredict#205]
I managed to get a local SocialPredict instance running with Docker and WSL2 in early July/late June. Now WSL2 tells me it can't find the Docker install.

Look into this so that users can run local instances consistently with WSL2.

**Comment by ntoufoudis** [comment]
Could you outline the steps you followed to run it on WSL2?

**Comment by astrosnat** [comment]
> Could you outline the steps you followed to run it on WSL2?

Yep!
1. Install vscode on WSL2
2. Through vscode, install the Docker extension
3. (I already have Docker Desktop for win11 with WSL2 support enabled)
4. Try to run ./compose-dev on WSL2 in my /socialpredict
5. See the attached screenshot for results:
![Screenshot 2024-07-14 111327](https://github.com/user-attachments/assets/b0d5ff65-d097-46b8-8b9f-6ac73e78dbcc)

**Comment by ntoufoudis** [comment]
When you try to access docker through Windows terminal and not through the wsl distribution, does it work?

**Comment by astrosnat** [comment]
> When you try to access docker through Windows terminal and not through the wsl distribution, does it work?

Yes, I can access Docker Desktop fine on win11. It just seems like WSL2 forgot I have Docker.

**Comment by astrosnat** [comment]
Update: I updated my Docker extension in VSCode inside WSL2, and now that worked.

**Comment by ntoufoudis** [comment]
> Update: I updated my Docker extension in VSCode inside WSL2, and now that worked.

VSCode has nothing to do with Docker itself, so I don't think this is the issue.

**Comment by astrosnat** [comment]
> VSCode has nothing to do with Docker itself, so I don't think this is the issue.

Should I reopen this issue, then? I'm just confused that it started working again.

**Comment by ntoufoudis** [comment]
# Steps for installing Docker on Windows:

## This procedure was followed on a Windows 10 Pro machine but it should also work on Windows 11

1. Open Powershell as administrator and run:
```wsl --install```
Wait for the operation to finish and restart your machine.

2. After restarting the machine, the Ubuntu installation will begin. Wait until it finishes and make sure you enter a username and password.

3. After installation is complete, you will automatically be logged in to Ubuntu. You can exit by typing:
```exit```

4. Open again Powershell and run:
```wsl --version```
Make sure WSL Version is 2.

5. Visit [Docker](https://docs.docker.com/desktop/install/windows-install/) and download Docker for Windows.

6. Run the downloaded file and proceed with the installation:
* Make sure to select "Use WSL 2 instead of Hyper-V"
* Wait for the installer to finish unpacking files
* When it finished make sure to click "Close and log out"
* After logging in again you will be provided with Docker Service Agreement. Make sure to accept it.
* Then Docker will start and offers you the option to Sign Up, Login or Continue without signing in. Make your choice.
* Then you can either complete the survey or skip it.
* After that Docker will be up and running. You can verify by checking on the bottom left part of Docker: "Engine Running".

7. Then open "Command Prompt(CMD)" or "Powershell" and run:
```docker --version```
```docker compose version```
* If you did everything correctly you should see the version of both commands.

8. Now you can run Docker and Docker Compose on your Windows Machine. In order to run it you need to make sure Docker Desktop is running on your machine.

9. If you wish to run docker via the WSL VM, just search for "Ubuntu" and click on it. When the machine starts up and you are logged in you can run docker inside the VM.

10. If Docker Desktop is not running, you won't be able to run docker or docker compose. You will most likely get an error saying docker not found.

**Comment by astrosnat** [comment]
Thank you...yes, out of everything, I wasn't doing step #10. :')
